### ISSUE TITLE
CPANTesters Backend processing is slow

### ISSUE THREAD

**Issue by preaction** [cpan-testers/cpantesters-project#14]
One user is reporting more than 6 hours from when a report is sent to the Metabase for it to be available on the CPANTesters website. I need to trace the code involved and figure out where all the bottlenecks are: Is it the polling frequency? Is it the server being overloaded? Is it the file generator processes not running often enough?

**Comment by barbie** [comment]
This is likely to be the Builder not the feed from the Metabase. Sometimes the order and frequency of building can need tweaking. See $quickhit in Process(), within https://metacpan.org/source/BARBIE/CPAN-Testers-WWW-Reports-3.57/lib/Labyrinth/Plugin/CPAN/Builder.pm

The general settings are in the config/settings.ini file, and there are two threads running (authors and distros), but I did want to try figuring out a MessageQueue system, that could run with multiple listeners, but sadly never got round to it.

**Comment by preaction** [comment]
For the message queue thing, I've got an interesting solution for that: [Mercury](http://metacpan.org/pod/Mercury). It's a message broker that uses websockets, is pure-Perl, easy to install, and lightweight. If the Metabase wrote updates to Mercury, and then the CPANTesters processor workers subscribed to Mercury, we could make that work. I was already kind of thinking about using Mercury to set up a Metabase feed, or even the actual logging (#13).

The only thing Mercury will need before it can be used is an authentication scheme to ensure that only authorized users are allowed to use it. Messages should only be sent by us, but in the future we may want messages to be received by anyone (and could then relax that part of the broker).

**Comment by preaction** [comment]
The new Minion-based backend has reduced processing times to mere minutes. It's not 100% perfect: The Metabase shim API directly inserts a Minion job. It would be better if it was less tightly coupled: Each test report write should pass a message on the message queue, and a backend process should read that queue to for processing. But, it works fast, so this ticket can be closed.
